version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
    networks:
      - app-network


networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local